# Generated by Django 4.2.5 on 2023-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
