# Generated by Django 4.2.5 on 2024-01-13 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be 18 digits starting with '+'.", regex='^+\\d{18}$')]),
        ),
    ]
