# Generated by Django 4.2.5 on 2024-01-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Regular User'), (1, 'Administrator')], default=1, verbose_name='User Type'),
        ),
    ]
