# Generated by Django 4.2.5 on 2024-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0011_remove_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Regular User'), (1, 'Administrator')], default=0, verbose_name='User Type'),
        ),
    ]
